#ifndef PRINTF_CONFIG_H
#define PRINTF_CONFIG_H

#define PRINTF_ALIAS_STANDARD_FUNCTION_NAMES 1

#ifndef AX_CONFIG_FP_SIMD

#define PRINTF_SUPPORT_DECIMAL_SPECIFIERS 0

#define PRINTF_SUPPORT_EXPONENTIAL_SPECIFIERS 0

#endif // AX_CONFIG_FP_SIMD

#endif // PRINTF_CONFIG_H
