[package]
name = "plic"
version = "0.1.0"
edition = "2021"
authors = ["KuangjuX"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tock-registers = "0.8"
log = "0.4"
