[package]
name = "embassy-single"
authors = ["nostalgia <lv15623448685@gmail.com>"]
edition.workspace = true

[dependencies]
axstd = { workspace = true, optional = true }
axasync = { workspace = true, features = ["single", "time"] }
embassy-executor = { git = "https://github.com/embassy-rs/embassy", branch = "main", default-features = false }