[workspace]

[package]
name = "ext2fs_fuse"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
ext2fs = { path = "../crates/ext2fs" }
rand = "0.8.0"
log = "0.4.0"
env_logger = "0.9.0"