//! Platform constants and parameters for dummy.
//! Generated by build.rs, DO NOT edit!

/// Stack size of each task.
pub const TASK_STACK_SIZE: usize = 0x40000;
/// Number of timer ticks per second (Hz). A timer tick may contain several timer
/// interrupts.
pub const TICKS_PER_SEC: usize = 100;
/// Architecture identifier.
pub const ARCH: &str = "unknown";
/// Platform identifier.
pub const PLATFORM: &str = "dummy";
/// Base address of the whole physical memory.
pub const PHYS_MEMORY_BASE: usize = 0;
/// Size of the whole physical memory.
pub const PHYS_MEMORY_SIZE: usize = 0;
/// Base physical address of the kernel image.
pub const KERNEL_BASE_PADDR: usize = 0;
/// Base virtual address of the kernel image.
pub const KERNEL_BASE_VADDR: usize = 0;
/// Linear mapping offset, for quick conversions between physical and virtual
/// addresses.
pub const PHYS_VIRT_OFFSET: usize = 0;
/// MMIO regions with format (`base_paddr`, `size`).
pub const MMIO_REGIONS: &[(usize, usize)] = &[
];
/// VirtIO MMIO regions with format (`base_paddr`, `size`).
pub const VIRTIO_MMIO_REGIONS: &[(usize, usize)] = &[
];
/// Base physical address of the PCIe ECAM space.
pub const PCI_ECAM_BASE: usize = 0;
/// End PCI bus number.
pub const PCI_BUS_END: usize = 0;
/// PCI device memory ranges.
pub const PCI_RANGES: &[(usize, usize)] = &[
];
/// Timer interrupt frequency in Hz.
pub const TIMER_FREQUENCY: usize = 0;
/// Number of CPUs
pub const SMP: usize = 1;
