on:
  push:
    branches: [ staging, trying, master ]
  pull_request:

name: Continuous integration

env:
  RUSTFLAGS: '--deny warnings'

jobs:
  ci-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # All generated code should be running on stable now
        rust: [stable]

        # The default target we're compiling on and for
        TARGET: [x86_64-unknown-linux-gnu, thumbv6m-none-eabi, thumbv7m-none-eabi]

        include:
          - rust: 1.31.0
            TARGET: x86_64-unknown-linux-gnu

          # Test nightly but don't fail
          - rust: nightly
            experimental: true
            TARGET: x86_64-unknown-linux-gnu

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.TARGET }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: check
          args: --target=${{ matrix.TARGET }}

      - uses: actions-rs/cargo@v1
        with:
          command: check
          args: --target=${{ matrix.TARGET }} --features unproven

