[package]
name = "deptool"
version = "0.1.0"
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
 clap = {version = "4.3.5"}
[workspace]
