extern crate cbindgen;

use std::env;

fn main() {
    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let config = cbindgen::Config {
        language: cbindgen::Language::C,
        cpp_compat: true,
        no_includes: false,
        usize_is_size_t: true,
        header: Some("/* Generated by cbindgen and build.rs, DO NOT edit! */".into()),
        ..Default::default()
    };

    cbindgen::generate_with_config(crate_dir, config)
        .expect("Unable to generate bindings")
        .write_to_file("libax.h");
}
