[package]
name = "axasync"
version.workspace = true
edition.workspace = true
authors = [""]
description = "ArceOS user library with an interface similar to rust std"
license.workspace = true
homepage.workspace = true
repository = "https://github.com/arceos-org/arceos/tree/main/ulib/axasync"

[features]
default = []

preempt = [
	"axfeat/async-preempt",
	"arceos_api/async-preempt",
	"thread",
]
thread = [
	"axfeat/async-thread",
	"arceos_api/async-thread",
	"dep:embassy-executor",
]
single = [
	"axfeat/async-single",
	"arceos_api/async-single",
	"dep:embassy-executor",
]

time = ["dep:embassy-time"]
sync = ["dep:embassy-sync"]

[dependencies]
axfeat = { workspace = true }
arceos_api = { workspace = true }

embassy-executor = { git = "https://github.com/embassy-rs/embassy", branch = "main", default-features = false, optional = true }
embassy-futures = { git = "https://github.com/embassy-rs/embassy", branch = "main" }
embassy-sync = { git = "https://github.com/embassy-rs/embassy", branch = "main", optional = true }
embassy-time = { git = "https://github.com/embassy-rs/embassy", branch = "main", optional = true }

cfg-if = "1.0.0"
static_cell = "2.1.0"
