name: Code formatting check

on:
  push:
    branches: [ staging, trying, main ]
  pull_request:

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check fmt
        run: cargo fmt -- --check
