[package]
name = "rosmaster-x3"
version = "0.1.0"
edition = "2021"
authors = ["limingth", "Luoyuan Xiao"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["axstd/paging"]

[dependencies]
axstd = { path = "../../../ulib/axstd", optional = true }
dw_apb_uart = { path = "../../../crates/dw_apb_uart" }
