//此模块负责管理LoongArch有关TLB和页表的寄存器与相关功能
mod asid;
mod pgd;
mod pgdh;
mod pgdl;
pub mod pwch;
pub mod pwcl;
mod stlbps;
mod tlbehi;
mod tlbelo;
mod tlbentry;
mod tlbidx;
mod tlbrbadv;
mod tlbrehi;
mod tlbrelo;
mod tlbrera;
mod tlbrprmd;
mod tlbrsave;

pub use asid::Asid;
pub use pgd::Pgd;
pub use pgdh::Pgdh;
pub use pgdl::Pgdl;
pub use pwch::Pwch;
pub use pwcl::Pwcl;
pub use stlbps::StlbPs;
pub use tlbehi::TlbEHi;
pub use tlbelo::{TLBEL, TLBELO};
pub use tlbentry::TLBREntry;
pub use tlbidx::TlbIdx;
pub use tlbrbadv::TlbRBadv;
pub use tlbrehi::TlbREhi;
pub use tlbrelo::TlbRelo;
pub use tlbrera::TLBREra;
pub use tlbrprmd::TlbRPrmd;
