[package]
name = "bwbench-client"
version = "0.1.0"
edition.workspace = true
authors = ["ChengXiang Qi <kuangjux@outlook.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
libc = "0.2.18"

[workspace]