./runtest.exe -w entry-dynamic.exe argv
./runtest.exe -w entry-dynamic.exe basename
./runtest.exe -w entry-dynamic.exe clocale_mbfuncs
./runtest.exe -w entry-dynamic.exe clock_gettime
./runtest.exe -w entry-dynamic.exe crypt
./runtest.exe -w entry-dynamic.exe dirname
./runtest.exe -w entry-dynamic.exe dlopen
./runtest.exe -w entry-dynamic.exe env
./runtest.exe -w entry-dynamic.exe fdopen
./runtest.exe -w entry-dynamic.exe fnmatch
./runtest.exe -w entry-dynamic.exe fscanf
./runtest.exe -w entry-dynamic.exe fwscanf
./runtest.exe -w entry-dynamic.exe iconv_open
./runtest.exe -w entry-dynamic.exe inet_pton
./runtest.exe -w entry-dynamic.exe mbc
./runtest.exe -w entry-dynamic.exe memstream
./runtest.exe -w entry-dynamic.exe pthread_cancel_points
./runtest.exe -w entry-dynamic.exe pthread_cancel
./runtest.exe -w entry-dynamic.exe pthread_cond
./runtest.exe -w entry-dynamic.exe pthread_tsd
./runtest.exe -w entry-dynamic.exe qsort
./runtest.exe -w entry-dynamic.exe random
./runtest.exe -w entry-dynamic.exe search_hsearch
./runtest.exe -w entry-dynamic.exe search_insque
./runtest.exe -w entry-dynamic.exe search_lsearch
./runtest.exe -w entry-dynamic.exe search_tsearch
./runtest.exe -w entry-dynamic.exe sem_init
./runtest.exe -w entry-dynamic.exe setjmp
./runtest.exe -w entry-dynamic.exe snprintf
./runtest.exe -w entry-dynamic.exe socket
./runtest.exe -w entry-dynamic.exe sscanf
./runtest.exe -w entry-dynamic.exe sscanf_long
./runtest.exe -w entry-dynamic.exe stat
./runtest.exe -w entry-dynamic.exe strftime
./runtest.exe -w entry-dynamic.exe string
./runtest.exe -w entry-dynamic.exe string_memcpy
./runtest.exe -w entry-dynamic.exe string_memmem
./runtest.exe -w entry-dynamic.exe string_memset
./runtest.exe -w entry-dynamic.exe string_strchr
./runtest.exe -w entry-dynamic.exe string_strcspn
./runtest.exe -w entry-dynamic.exe string_strstr
./runtest.exe -w entry-dynamic.exe strptime
./runtest.exe -w entry-dynamic.exe strtod
./runtest.exe -w entry-dynamic.exe strtod_simple
./runtest.exe -w entry-dynamic.exe strtof
./runtest.exe -w entry-dynamic.exe strtol
./runtest.exe -w entry-dynamic.exe strtold
./runtest.exe -w entry-dynamic.exe swprintf
./runtest.exe -w entry-dynamic.exe tgmath
./runtest.exe -w entry-dynamic.exe time
./runtest.exe -w entry-dynamic.exe tls_init
./runtest.exe -w entry-dynamic.exe tls_local_exec
./runtest.exe -w entry-dynamic.exe udiv
./runtest.exe -w entry-dynamic.exe ungetc
./runtest.exe -w entry-dynamic.exe utime
./runtest.exe -w entry-dynamic.exe wcsstr
./runtest.exe -w entry-dynamic.exe wcstol
./runtest.exe -w entry-dynamic.exe daemon_failure
./runtest.exe -w entry-dynamic.exe dn_expand_empty
./runtest.exe -w entry-dynamic.exe dn_expand_ptr_0
./runtest.exe -w entry-dynamic.exe fflush_exit
./runtest.exe -w entry-dynamic.exe fgets_eof
./runtest.exe -w entry-dynamic.exe fgetwc_buffering
./runtest.exe -w entry-dynamic.exe fpclassify_invalid_ld80
./runtest.exe -w entry-dynamic.exe ftello_unflushed_append
./runtest.exe -w entry-dynamic.exe getpwnam_r_crash
./runtest.exe -w entry-dynamic.exe getpwnam_r_errno
./runtest.exe -w entry-dynamic.exe iconv_roundtrips
./runtest.exe -w entry-dynamic.exe inet_ntop_v4mapped
./runtest.exe -w entry-dynamic.exe inet_pton_empty_last_field
./runtest.exe -w entry-dynamic.exe iswspace_null
./runtest.exe -w entry-dynamic.exe lrand48_signextend
./runtest.exe -w entry-dynamic.exe lseek_large
./runtest.exe -w entry-dynamic.exe malloc_0
./runtest.exe -w entry-dynamic.exe mbsrtowcs_overflow
./runtest.exe -w entry-dynamic.exe memmem_oob_read
./runtest.exe -w entry-dynamic.exe memmem_oob
./runtest.exe -w entry-dynamic.exe mkdtemp_failure
./runtest.exe -w entry-dynamic.exe mkstemp_failure
./runtest.exe -w entry-dynamic.exe printf_1e9_oob
./runtest.exe -w entry-dynamic.exe printf_fmt_g_round
./runtest.exe -w entry-dynamic.exe printf_fmt_g_zeros
./runtest.exe -w entry-dynamic.exe printf_fmt_n
./runtest.exe -w entry-dynamic.exe pthread_robust_detach
./runtest.exe -w entry-dynamic.exe pthread_cond_smasher
./runtest.exe -w entry-dynamic.exe pthread_condattr_setclock
./runtest.exe -w entry-dynamic.exe pthread_exit_cancel
./runtest.exe -w entry-dynamic.exe pthread_once_deadlock
./runtest.exe -w entry-dynamic.exe pthread_rwlock_ebusy
./runtest.exe -w entry-dynamic.exe putenv_doublefree
./runtest.exe -w entry-dynamic.exe regex_backref_0
./runtest.exe -w entry-dynamic.exe regex_bracket_icase
./runtest.exe -w entry-dynamic.exe regex_ere_backref
./runtest.exe -w entry-dynamic.exe regex_escaped_high_byte
./runtest.exe -w entry-dynamic.exe regex_negated_range
./runtest.exe -w entry-dynamic.exe regexec_nosub
./runtest.exe -w entry-dynamic.exe rewind_clear_error
./runtest.exe -w entry-dynamic.exe rlimit_open_files
./runtest.exe -w entry-dynamic.exe scanf_bytes_consumed
./runtest.exe -w entry-dynamic.exe scanf_match_literal_eof
./runtest.exe -w entry-dynamic.exe scanf_nullbyte_char
./runtest.exe -w entry-dynamic.exe setvbuf_unget
./runtest.exe -w entry-dynamic.exe sigprocmask_internal
./runtest.exe -w entry-dynamic.exe sscanf_eof
./runtest.exe -w entry-dynamic.exe statvfs
./runtest.exe -w entry-dynamic.exe strverscmp
./runtest.exe -w entry-dynamic.exe syscall_sign_extend
./runtest.exe -w entry-dynamic.exe tls_get_new_dtv
./runtest.exe -w entry-dynamic.exe uselocale_0
./runtest.exe -w entry-dynamic.exe wcsncpy_read_overflow
./runtest.exe -w entry-dynamic.exe wcsstr_false_negative
